"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
This file is vendored locally from the in-flight OTEP 4719 (Process Context
Sharing). Once OTEP 4719 lands in upstream opentelemetry-proto, this file
should be removed and the generated bindings should come from the upstream
`scripts/proto_codegen.sh` flow.

Source:
https://github.com/open-telemetry/opentelemetry-specification/pull/4719
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import opentelemetry.proto.common.v1.common_pb2
import opentelemetry.proto.resource.v1.resource_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ProcessContext(google.protobuf.message.Message):
    """ProcessContext represents the payload for the process context sharing mechanism.

    This message is designed to be published by OpenTelemetry SDKs via a memory-mapped
    region, allowing external readers (such as the OpenTelemetry eBPF Profiler) to
    discover and read resource attributes from instrumented processes without requiring
    direct integration or process activity.

    Status: [Development]
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    @property
    def resource(self) -> opentelemetry.proto.resource.v1.resource_pb2.Resource:
        """The resource attributes describing this process.

        Attribute keys MUST be unique (it is not allowed to have more than one
        attribute with the same key). The behavior of software that receives
        duplicated keys can be unpredictable.

        Attributes SHOULD follow OpenTelemetry semantic conventions where applicable.
        See: https://opentelemetry.io/docs/specs/semconv/
        """
    @property
    def attributes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[opentelemetry.proto.common.v1.common_pb2.KeyValue]:
        """Additional attributes to share with external readers that are not part of
        the standard Resource. [Optional]

        This field allows publishers to include supplementary key-value pairs that
        may be useful for external readers but are not part of the SDK's configured
        Resource.

        Consider adding any keys here to the profiles semantic conventions in
        https://opentelemetry.io/docs/specs/semconv/general/profiles/
        """
    def __init__(
        self,
        *,
        resource: opentelemetry.proto.resource.v1.resource_pb2.Resource | None = ...,
        attributes: collections.abc.Iterable[opentelemetry.proto.common.v1.common_pb2.KeyValue] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource", b"resource"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["attributes", b"attributes", "resource", b"resource"]) -> None: ...

global___ProcessContext = ProcessContext
