# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/processcontext/v1development/process_context.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opentelemetry.proto.common.v1 import common_pb2 as opentelemetry_dot_proto_dot_common_dot_v1_dot_common__pb2
from opentelemetry.proto.resource.v1 import resource_pb2 as opentelemetry_dot_proto_dot_resource_dot_v1_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFopentelemetry/proto/processcontext/v1development/process_context.proto\x12\x30opentelemetry.proto.processcontext.v1development\x1a*opentelemetry/proto/common/v1/common.proto\x1a.opentelemetry/proto/resource/v1/resource.proto\"\x8a\x01\n\x0eProcessContext\x12;\n\x08resource\x18\x01 \x01(\x0b\x32).opentelemetry.proto.resource.v1.Resource\x12;\n\nattributes\x18\x02 \x03(\x0b\x32\'.opentelemetry.proto.common.v1.KeyValueB\xbc\x01\n3io.opentelemetry.proto.processcontext.v1developmentB\x13ProcessContextProtoP\x01Z;go.opentelemetry.io/proto/otlp/processcontext/v1development\xaa\x02\x30OpenTelemetry.Proto.ProcessContext.V1Developmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentelemetry.proto.processcontext.v1development.process_context_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n3io.opentelemetry.proto.processcontext.v1developmentB\023ProcessContextProtoP\001Z;go.opentelemetry.io/proto/otlp/processcontext/v1development\252\0020OpenTelemetry.Proto.ProcessContext.V1Development'
  _globals['_PROCESSCONTEXT']._serialized_start=217
  _globals['_PROCESSCONTEXT']._serialized_end=355
# @@protoc_insertion_point(module_scope)
